### PR TITLE
feat(chore): updated lib versions in ng-nx-v15 example

### PR DESCRIPTION
**Pull request by SvetlanaMuravlova**

### CODE REVIEW

**Comment by SvetlanaMuravlova** [comment]
Screenshot 2024-09-06 at 16 13 31
https://svetlana_muravlova_valor-software_com_38-nx-v15-n-136f83fd5-ze.zephyrcloud.app/

**Comment by SvetlanaMuravlova** [comment]
fixed, links work correctly https://svetlana_muravlova_valor-software_com_40-nx-v15-n-ee1235457-ze.zephyrcloud.app/

**Comment by VladyslavZinchenko** [comment]
Have an issue with ssetsimage

**Comment by SvetlanaMuravlova** [comment]
https://svetlana_muravlova_valor-software_com_107-nx-v15--4affe31a3-ze.zephyrcloud.app/

**Review by ryok90 — APPROVED** [review]

**Pull request merged**
